stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image

  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - WEIGHTS
      - CLASSES
      - INCLUDE_TOP
    outs:
      - artifacts/prepare_base_model
  

  training:
    cmd: python src/cnnClassifier/pipeline/stage_03_model_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_training.py
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
      - config/config.yaml
    params:
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - IMAGE_SIZE
    
    outs:
      - artifacts/training/trained_model.h5

  evoluation:
    cmd: python src/cnnClassifier/pipeline/stage_04_model_evolution_mlflow.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_model_evolution_mlflow.py
      - config/config.yaml
      - artifacts/training/trained_model.h5
      - artifacts/data_ingestion/kidney-ct-scan-image
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - source.json:
          cache: false
    